### ISSUE TITLE
[NEXUS / PRISMA] No Subscription Support

### ISSUE THREAD

**Issue by Stevenje** [lewebsimple/fullstack-boilerplate#10]
Unfortunately it looks like there is no Subscription Support in Prisma 2 / Nexus at the moment which is a bit of a deal killer :/ 

https://github.com/prisma/prisma/issues/298

Shame as I really liked the Prisma 2 backend experience. 

I'm happy to use a hosted GraphQL backend like slash dgraph or hasura although don't know if you have any alternative tech stack solutions (Node Client Library) which give as good strong TS experience. Similar to Villus on the frontend, Tell Node client where schema is and it pulls in data / types and gives autocomplete on arguments and return data types.

**Comment by lewebsimple** [comment]
You can generate the gql operations from the schema on other platforms and get the same frontend DX. It's just a matter of configuring GraphQL Codegen / gql-generator properly and you should be good to go.

**Comment by Stevenje** [comment]
@lewebsimple The problems the backend. I'm very happy with the frontend experience using villus / graphQL codegen. 

I would be looking for a similar experience on NodeJS (that also being a client)

Although I think I'm going to stick with this setup for the time being and wait for subscriptions to come out and in the interim just poll the server every minute as I'm building a dashboard it does not have to be perfect realtime for my needs.

**Comment by osintops** [comment]
Wow no realtime subscription support... deal killer as well, massive let down.

**Comment by lewebsimple** [comment]
@osintops subscriptions work just fine if you define them manually. The actual limitation from Prisma / nexus-plugin-prisma is that you can’t project them declaratively with something like ‘t.crud.something’

**Comment by osintops** [comment]
Yeah for a junior developer I have no idea what your on about lol, ideally it should be provided and baked into the documentation and I assume that's the entire reason for abstractions and using libraries and ORMs (make things simple). Prisma 1 it was provided and well documented, now nothing. I am not the only one that feels this way, as the feature of subscriptions has been requested in previous threads. Realtime connectivity and streaming data is the way of the web now, not sure why you dropped such amazing feature set. Am I missing something here?
