### ISSUE TITLE
feat: Refactor server using Mercurius

### ISSUE THREAD

**Issue by Stevenje** [lewebsimple/fullstack-boilerplate#11]
**Benchmarks**

- Typically on a MongoDB Atlas, Node Rest API I'm getting a response time of 130ms.
- On https://slash.dgraph.io/ I was getting around 150-200ms
- I'm currently getting around 350-400ms on a simple mutation request (DB is AWS RDS - Postgresql, Free Tier) and I'm assuming as my data gets more complex it would slow down further.

Is this normal for a GraphQL instance? This was also all run locally apart from backend DB. Brand new DB as well. Ran mutation multiple times and every time it was slow. Also project was ran after being built using `yarn start`. 

Any insights? 

![image](https://user-images.githubusercontent.com/4363358/97030826-fb0ef700-1524-11eb-8266-07bf28e2081b.png)

![image](https://user-images.githubusercontent.com/4363358/97030953-2b569580-1525-11eb-8f91-a4805f4409e0.png)

```ts
import { CreateOneReportDocument } from "../generated/graphql-operations";

export default defineComponent({
  name: "HelloWorld",
  setup() {
    const returnData = ref();
    async function main() {
      const { data, error } = await useMutation(
        CreateOneReportDocument,
      ).execute({
        data: { type: "Keyword", date: new Date() },
      });
      console.log("Mutation:", data, error);
      returnData.value = data;
    }

    main();

    return { returnData };
  },
});
</script>
```

**Comment by lewebsimple** [comment]
There is some overhead caused by Nexus-Shield, it can be made faster by [caching](https://github.com/Sytten/nexus-shield#caching).
There could be other issues related to the hosting setup on AWS (opening the DB connection comes to mind), running benchmarks locally would give us the real picture.

**Comment by lewebsimple** [comment]
Is it only for mutations or are query slow as well ?

**Comment by Stevenje** [comment]
I'll check now but I did find this in terms of benchmarks if we're able to swap out the underlying server for a faster one 

https://github.com/benawad/node-graphql-benchmarks

**Comment by Stevenje** [comment]
Much better on a basic Query. Around 150ms

**Comment by Stevenje** [comment]
Although based on the benchmarks`apollo-server-express` is one of the slower servers. 

Not sure if we're tied to `apollo-server-express` due to integration with Prisma / Nexus although it looks like `fastify-gql+graphql-jit` is the current king or if we want to stay with Express, `express-gql` looks to be a good option, which can handle 3x's the amount of requests per second.

**Comment by lewebsimple** [comment]
Good to know... it can be changed easily.

**Comment by lewebsimple** [comment]
Looks like `fastify-gql` has been renamed to [mercurius](https://github.com/mercurius-js/mercurius).

**Comment by Stevenje** [comment]
Thats great! Are you planning to implement fastify-gql / mercurous with graphql-jit? Otherwise [express-gql](https://github.com/benawad/express-gql) looks potentially a better option. Although not sure if it supports Nexus Schema. 

<img width="659" alt="image" src="https://user-images.githubusercontent.com/4363358/97107235-7d69f900-1694-11eb-8f1e-44e6e51fcf8c.png">

Anyway, either way sounds like a nice upgrade!

**Comment by Stevenje** [comment]
Also when I was looking into how to provide support for Subscriptions while Prisma 2/ Nexus worked on their implementation, https://github.com/prisma-labs/graphql-yoga kept coming up as a fix in the interim.

**Comment by lewebsimple** [comment]
Backend is now based on Fasity / Mercurius :rocket:  !
