### ISSUE TITLE
[Updates] Vite / Vue Router

### ISSUE THREAD

**Issue by Stevenje** [lewebsimple/fullstack-boilerplate#13]
Morning! 

Hope you're having a good weekend, 

Nice updates out rc6 for Vite + Rc for Vue Router :D

**Comment by lewebsimple** [comment]
This is already in 0.2.0.
Dependency updates are usually taken care of quite fast, so there's no need to report them in an issue unless it introduces some breaking changes worth discussing.

**Comment by Stevenje** [comment]
@lewebsimple Sounds great is 0.2 going to be released today?
