### ISSUE TITLE
[QUESTION] Segment Prisma Aggregation 

### ISSUE THREAD

**Issue by Stevenje** [lewebsimple/fullstack-boilerplate#15]
Hey @lewebsimple I would love your advice on something. 

I have some date like the following (in reality its much more complex) that has a main Report Type (representing 1 days data) and then Items is an array of a type called ReportItem

```
Report type {
Date: XX Oct
Items: [ReportItem, ReportItem]
}
```

**Example Data**
```
Report 1 {
Date: 21 Oct
Items: [{query: A, views: 20}, {query: B, views: 70 }]
}

Report 2 {
Date: 22 Oct
Items: [{query: A, views: 32}, {query: B, views: 27 }]
}

Report 3 {
Date: 23 Oct
Items: [{query: A, views: 13}, {query: B, views: 65 }]
}
```

I would like to aggregate the reports into a new report for the dates a user selects that displays the total views of each query for that time period.

Eg 21-23 Oct. 
{ query A: 65, query B: 162 }

Although when I use aggregate there's no way to split it up by query it just sums up all views.

```ts
const generated = await prisma.reportItem.aggregate({
        sum: {
          views: true,
        },
})
```

Do you know a way I can do this without having to map through each query individually and do separate DB requests for each query?

```
await Promise.all(
    reportItems.map(async (reportItem) => {
      const generated = await prisma.reportItem.aggregate({
        sum: {
          views: true,
        },

        where: {
          query: reportItem.query,
        },

      });
      console.log(reportItem.query, generated.sum );
    }),
  );
```

Open to changing schema, although even if I put all query A views data in the same object I'd still have to do 1 request per query. 

Thanks a lot mate!

PS loving this stack!

**Comment by lewebsimple** [comment]
Hum... haven't played much with aggregate yet, but my guess is having 2 requests shouldn't be such a big deal (if you had 100 or more, then it might be).
[Premature optimization is the root of all evil](https://stackify.com/premature-optimization-evil/)

**Comment by Stevenje** [comment]
Haha yes I have over 600 currently going off :)
