### ISSUE TITLE
Add eslint-Vue-Beta 

### ISSUE THREAD

**Issue by Stevenje** [lewebsimple/fullstack-boilerplate#2]
https://www.npmjs.com/package/eslint-plugin-vue/v/5.0.0-beta.4 - supports vue 3

**Comment by lewebsimple** [comment]
I fixed the ESLint / Prettier config for Vue... turns out plugin:@typescript-eslint/recommended has to come before the Vue stuff in .eslintrc
We also need to use `defineComponent` in SFC to please the TypeScript gods.

**Comment by Stevenje** [comment]
@lewebsimple Hahah, although I believe you just need to use the beta then all the issues go away.  (eslint-plugin-vue@next)
