### ISSUE TITLE
Add tailwind for css

### ISSUE THREAD

**Issue by Stevenje** [lewebsimple/fullstack-boilerplate#3]
I'm currently using this as a great front end starter https://github.com/posva/vite-tailwind-starter potentially switch it out with what is currently there in the frontend folder.

**Comment by lewebsimple** [comment]
I've added TailwindCSS / Vue-Router but not the default markup from the repository you linked.
I almost got `import.meta.hot` to work but I was having problems with the tsconfig module resolution (long story short, you have to use ESNext module but this breaks import statements elsewhere). We might need a separate tsconfig for frontend,,

**Comment by Stevenje** [comment]
OK that should be fine in the interim.

**Comment by lewebsimple** [comment]
Closing this issue since TailwindCSS is configured, let's tackle the `import.meta` and default views in separate issues.
