### ISSUE TITLE
[DOCS] Where should schema be defined? 

### ISSUE THREAD

**Issue by Stevenje** [lewebsimple/fullstack-boilerplate#4]
Where should schema be defined? So that it propagates across Prisma, Vue & Apollo server. 

What commands need to be also then run when schema is updated.

**Comment by lewebsimple** [comment]
Check out the new [Schema Workflow](https://github.com/lewebsimple/fullstack-boilerplate/blob/master/docs/schema-workflow.md) documentation !

**Comment by Stevenje** [comment]
Morning @lewebsimple Thanks a lot for that. That really helps!

Quick question I moved across to GraphQL to as I wanted to define a model and then instantly have CRUD access to it from the front end without having to write an API end point for each operation. And then restrict it so that when a `User` requests `Messages`, only his messages are returned. Thats the basic workflow. 

Although if I have to write the `schema/types` manually (I believe the resolvers) it doesn't seem to be saving me much time vs writing API endpoints before. I would understand if it was custom logic like login but this seems pretty standard for each one. 

Previously I was using https://slash.dgraph.io/ and there I just defined the schema and was able to use GraphQL-codegen to do the` TypedNodeDocuement` and instantly have access to all CRUD options without having to write the resolvers. Are we able to replicate that or am I missing something?

**Comment by Stevenje** [comment]
Actually, I think I'm starting to get it, essentially here you're just saying what the front end has access to of the CRUD operations for example you might only want the user to be able to Read Posts not Update for example. 

Also I'm guessing you can state something like when the frontend requests User it returns the current User or when the Front End asks for Messages its just the Users messages.

**Comment by Stevenje** [comment]
Although it would be nice if it auto generated it so that all CRUD operations were available by default (and just returned all fields) and then i could later edit and fine tune to restrict access.
